name: Build and release


permissions:
  id-token: write
  packages: write
  contents: read
  attestations: write

on:
  workflow_call:
    secrets:
      GPG_SECRET_KEY:
        required: true
      GPG_PUBLIC_KEY:
        required: true
      GPG_PASS:
        required: true

jobs:
  extract-version:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - uses: actions/checkout@v5
      - name: Extract Version
        id: extract
        uses: ./.github/actions/get-version
    outputs:
      version: ${{ steps.extract.outputs.release-version }}

  build-packages:
    uses: aerospike/shared-workflows/.github/workflows/reusable_execute-build.yaml@e9d98e77b7895f22a3a45393f8461d44901df7be
    needs: extract-version
    with:
      runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
      jf-project: ${{ vars.JFROG_PROJECT }}
      jf-build-name: aerospike-client-java-fluent
      jf-build-id: ${{ github.run_number }}-buildinfo-${{ needs.extract-version.outputs.version }}
      gh-checkout-path: shared-workflows
      gh-source-path: aerospike-client-java-fluent
      working-directory: aerospike-client-java-fluent
      setup-java: true
      java-version: "${{ vars.JAVA_VERSION }}"
      java-distribution: ${{ vars.JAVA_DISTRIBUTION }}
      build-script: |
        mvn \
          --batch-mode \
          --no-transfer-progress \
          --update-snapshots \
          --fail-at-end \
          --errors \
          source:jar javadoc:javadoc clean package \
          -DskipTests

        for jar in client/target/*.jar; do
          if [[ ! "$jar" == *"-jar-with-dependencies.jar" ]]; then
            cp "$jar" build/
          fi
        done
      gh-artifact-directory: build
      gh-artifact-name: build-artifacts-${{ needs.extract-version.outputs.version }}
      gh-retention-days: 1 # default
      jf-url: https://artifact.aerospike.io # default
      publish-build-info: true
      oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
      oidc-audience: ${{ vars.OIDC_AUDIENCE }}

  sign-artifacts:
    needs: [build-packages, extract-version]
    uses: aerospike/shared-workflows/.github/workflows/reusable_sign-artifacts.yaml@37581d0437fe0b76315dafc402882c875789b1af
    with:
      gh-retention-days: 1
      gh-artifact-name: signed_build-artifacts-${{ needs.extract-version.outputs.version }}
      gh-unsigned-artifacts: build-artifacts-${{ needs.extract-version.outputs.version }}
    secrets:
      gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
      gpg-key-pass: ${{ secrets.GPG_PASS }}

  deploy-artifacts:
    needs: [sign-artifacts, extract-version]
    uses: aerospike/shared-workflows/.github/workflows/reusable_deploy-artifacts.yaml@20b5c89211e060da0e1118bc735bc1e616acf946
    with:
      gh-workflows-ref: 20b5c89211e060da0e1118bc735bc1e616acf946
      jf-project: ${{ vars.JFROG_PROJECT }}
      jf-build-name: aerospike-client-java-fluent
      jf-metadata-build-id: ${{ github.run_number }}-buildinfo
      jf-build-id: ${{ github.run_number }}
      gh-artifact-name: ${{ needs.sign-artifacts.outputs.gh-artifact-name }}
      version: ${{ needs.extract-version.outputs.version }}
      gh-retention-days: 1
      oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
      oidc-audience: ${{ vars.OIDC_AUDIENCE }}
      dry-run: false

  create-release-bundle:
    needs: [extract-version, deploy-artifacts]
    uses: aerospike/shared-workflows/.github/workflows/reusable_create-release-bundle.yaml@37581d0437fe0b76315dafc402882c875789b1af
    with:
      jf-project: ${{ vars.JFROG_PROJECT }}
      jf-build-names: aerospike-client-java-fluent:${{ github.run_number }}
      jf-bundle-name: aerospike-client-java-fluent
      version: ${{ needs.extract-version.outputs.version }}
      oidc-provider-name: ${{ vars.OIDC_PROVIDER_NAME }}
      oidc-audience: ${{ vars.OIDC_AUDIENCE }}
      dry-run: false
