name: Java Build & Release

on:
  push:
    branches:
      - CLIENT-3877
  workflow_dispatch:
  #   - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-stage:
    name: Build stage
    uses: ./.github/workflows/build-release.yaml@b81592e3b393b3db0321bf982dfab9cc2c19255e
    secrets: inherit

#jobs:
#  build-stage:
#    name: Build stage
#    uses: ./.github/workflows/release-stage.yaml
#    with:
#      ref: ${{ github.ref }}
#      build-number: ${{ github.run_number }}
#    secrets: inherit
#
